In [8]:
import pandas as pd
import numpy as np

df = pd.read_excel(r"C:\Users\user\Documents\data_aspek_pos.xlsx") #input dataset 
df #tampilkan

opini          aspek
0                                 berita cepat terkini        content
1                                    tarik berita baru        content
2                             berita bagus sesuai jadi        content
3                                       aplikasi henti  functionality
4    berita terkini mantap percaya maju cnn indones...        content
..                                                 ...            ...
995               profesional serang bijak perintah sa        content
996  berita ber ulang ulang muncul berita banyak ik...        content
997  berita diskredit pemerintahbila berita sampai ...        content
998                                  baik berita terus        content
999                                     hoax makan bos        content

[1000 rows x 2 columns]

In [9]:
df['aspek'].value_counts()

content              777
functionality        192
user interface        16
streaming quality     15
Name: aspek, dtype: int64

In [10]:
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer
vectorizer = CountVectorizer(decode_error="replace")
transformer = TfidfTransformer()
TFIDF = transformer.fit_transform(vectorizer.fit_transform(df['opini']))

In [11]:
print (TFIDF)

  (0, 1519)	0.5924283618913982
  (0, 301)	0.7578853615158642
  (0, 203)	0.27320031996072486
  (1, 1482)	0.6729059408194431
  (1, 203)	0.21677723549801212
  (1, 163)	0.7072518822737338
  (2, 1397)	0.566766929490242
  (2, 643)	0.721910996369818
  (2, 203)	0.18118446935185054
  (2, 123)	0.35325903954779125
  (3, 563)	0.8986765671302706
  (3, 87)	0.4386119329098928
  (4, 1519)	0.2517695255590892
  (4, 1174)	0.32379195307252456
  (4, 918)	0.6658473804821057
  (4, 892)	0.485435984873708
  (4, 606)	0.29047295335276574
  (4, 323)	0.23434011376259567
  (4, 203)	0.11610435854134919
  (5, 1519)	0.3789111895379337
  (5, 1174)	0.48730438614075494
  (5, 1023)	0.492613439306687
  (5, 587)	0.5101228831123124
  (5, 123)	0.34068664375133567
  (6, 1087)	0.9725689930811491
  :	:
  (995, 1309)	0.508194081052707
  (995, 1219)	0.45937583676241306
  (995, 1177)	0.32232569836784586
  (995, 227)	0.508194081052707
  (996, 1609)	0.7011906987170873
  (996, 998)	0.3018701821203632
  (996, 588)	0.4015925092163663
  

In [12]:
  #Save model TFIDF
import pickle
pickle.dump(vectorizer.vocabulary_,open("TFIDFmodel_kfold.pkl","wb"))

In [13]:
labels = [] #membuat kolom labels
for data in df['aspek']:#untuk data di df row kategori
    labels.append(data)
kolom = labels.pop
print(labels)

['content', 'content', 'content', 'functionality', 'content', 'content', 'content', 'content', 'functionality', 'content', 'user interface', 'content', 'functionality', 'functionality', 'content', 'content', 'functionality', 'streaming quality', 'content', 'content', 'content', 'content', 'content', 'content', 'content', 'content', 'content', 'streaming quality', 'content', 'content', 'functionality', 'content', 'content', 'content', 'content', 'content', 'content', 'content', 'functionality', 'functionality', 'content', 'content', 'content', 'functionality', 'content', 'content', 'content', 'functionality', 'content', 'streaming quality', 'content', 'content', 'content', 'content', 'content', 'content', 'content', 'content', 'content', 'streaming quality', 'content', 'content', 'content', 'content', 'user interface', 'content', 'content', 'content', 'content', 'content', 'streaming quality', 'content', 'content', 'content', 'content', 'content', 'functionality', 'content', 'functional

In [14]:
#kemudian kategori diberi label
label=[]
for i in range(len(labels)): 
    if labels[i]=='content':
        nilai = 0
        label.append(nilai)
    
    if labels[i]=='functionality':
        nilai = 1
        label.append(nilai)
    
    if labels[i]=='user interface':
        nilai = 2
        label.append(nilai)
        
    if labels[i]=='streaming quality':
        nilai = 3
        label.append(nilai)

In [15]:
print(len(label))
print(len(df))
print(label)

1000
1000
[0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 2, 0, 1, 1, 0, 0, 1, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 3, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 2, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 3, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 2, 0, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 2, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0,

In [47]:
from sklearn import svm #metode untuk klasifikasi aspek / kategori
from sklearn.feature_extraction.text import TfidfTransformer, CountVectorizer #untuk menghitung vsm dan tfidf #vsm =vector space model
from sklearn import metrics #metode untuk pembentukan matriks 1x1 1x2 1x3
from sklearn.metrics import accuracy_score #metod untuk pembentukan skor akurasi 
from sklearn.model_selection import KFold #metode untuk perhitungan kfold
import numpy as np 
import re #regular expression
import itertools #fungsi pengulangan tak terbatas
import matplotlib.pyplot as plt #pembentukan diagram
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC #suport vector classifier
from sklearn.metrics import classification_report

##packages untuk multiclass
from sklearn.multiclass import OneVsRestClassifier #pake library ovr
##from sklearn.svm import SVC
from sklearn.svm import LinearSVC

In [66]:
akurasi = []
akurasi1 =[]
def avg_akurasiRBF(): ## nama fungsi
    total = 0 ## pengosongan variabel
    for i in range(10): ## looping 10x karena ada 10 fold
        total = total + akurasi[i] ## tiap looping nilai total akan ditambahkan dengan nilai akurasi tiap fold
    print("Rata-rata akurasi keseluruhan SVM kernel RBF adalah :", total / 10)
    
def avg_akurasiOvR(): ##fungsi untuk rata rata akurasi one vs rest classifier
    total = 0
    for i in range(10): ##lakukan 10 kali
        total = total + akurasi1[i]
    print("Rata-rata akurasi keseluruhan SVM Multiclass One vs All adalah :", total / 10)

In [67]:
kFoldCrossValidation = KFold(n_splits=10)#fungsi K-Fold Cross Validation melakukan insialisasi 10 kali iterasi

In [70]:
from sklearn.multiclass import OneVsRestClassifier #pake library ovr
for latih, uji in kFoldCrossValidation.split(TFIDF, label):
    print("-----------------------------")
    print("Banyak Data Latih: ", len(latih)) #berapa jmlah data latih
    print("Banyak Data Uji: ", len(uji)) #berapa jumlah data uji
    print("\nData Latih: \n", latih) #menampilkan data latih
    print("\nData Uji: \n", uji)#menampilkan data uji
    dataLatih1, dataUji1 = TFIDF[latih], TFIDF[uji]#proses inisialisasi dari masing2 data latih/uji dijadikan nilai tfidf lalu di copy ke variabel dataLatih/Uji1
    label = np.array(label)
    dataLatih2, dataUji2 = label[latih], label[uji]#
    
    SVMRBF = svm.SVC(kernel ='rbf', gamma=0.7)
    modelRBF = SVMRBF.fit(dataLatih1, dataLatih2)#data latih melakukan proses pelatihan dengan algoritma SVM
    prediksi = modelLinear.predict(dataUji1)#proses prediksi dari data latih yang sudah tersimpan sebagai model
    
    SVMOvR = OneVsRestClassifier(LinearSVC(C=1))
    modelOvR = SVMOvR.fit(dataLatih1, dataLatih2)
    prediksi1 = modelOvR.predict(dataUji1)
    
    print("\nHasil Prediksi SVM KERNEL RBF: \n", prediksi)
    print("\nHasil Prediksi SVM One vs All : \n", prediksi1)
    
    print("\nConfusion Matrix: \n", metrics.confusion_matrix(dataUji2, prediksi))
    print("\nConfusion Matrix: \n", metrics.confusion_matrix(dataUji2, prediksi1))
    
    akurasi.append(accuracy_score(dataUji2, prediksi))
    akurasi.append(accuracy_score(dataUji2, prediksi1))
    
    print("\nAkurasi SVM RBF: ", accuracy_score(dataUji2, prediksi))
    print()\
    
    print("\nAkurasi SVM One vs All : ", accuracy_score(dataUji2, prediksi1))
    print()\
    
    label_target = ['content','functionality','user interface','streaming quality']
    print(metrics.classification_report(dataUji2, prediksi, labels=[0,1,2,3]))#proses pembentukan confusin matrix
    
avg_akurasiRBF() #hitung rata rata kernel rbf
avg_akurasiOvR() #hasil rata rata multiclass

-----------------------------
Banyak Data Latih:  900
Banyak Data Uji:  100

Data Latih: 
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135
 136 137 138 139 140 141 142 143 144 145 146 147 148 149 150 151 152 153
 154 155 156 157 158 159 160 161 162 163 164 165 166 167 168 169 170 171
 172 173 174 175 176 177 178 179 180 181 182 183 184 185 186 187 188 189
 190 191 192 193 194 195 196 197 198 199 200 201 202 203 204 205 206 207
 208 209 210 211 212 213 214 215 216 217 218 219 220 221 222 223 224 225
 226 227 228 229 230 231 232 233 234 235 236 237 238 239 240 241 242 243
 244 245 246 247 248 249 250 251 252 253 254 255 256 257 258 259 260 261
 262 263 264 265 266 267 268 269 270 271 272 273 274 275 276 277 278 279
 280 281 282 283 284 285 286 287 288 289 290 291 292 293 294 295 296 297
 298 299 300 301 302 303 304 305 306 307 308 309 310 311 312 313 314 315
 316 317 318 319 320 321 322 323 


Hasil Prediksi SVM KERNEL RBF: 
 [0 0 0 0 2 0 0 0 0 0 2 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 0 0 0 3 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 0 0 1 1 0 0 1 0 1 0 2 0 0
 0 0 0 0 1 2 0 0 0 0 0 0 2 0 0 1 0 0 0 0 0 0 0 0 0 0]

Hasil Prediksi SVM One vs All : 
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0
 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 0 1 0 0 0 1 0 0
 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]

Confusion Matrix: 
 [[81  0  0  0]
 [ 0 11  0  0]
 [ 0  1  5  0]
 [ 0  0  0  2]]

Confusion Matrix: 
 [[76  5  0  0]
 [ 3  8  0  0]
 [ 4  2  0  0]
 [ 0  2  0  0]]

Akurasi SVM RBF:  0.99


Akurasi SVM One vs All :  0.84

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        81
           1       0.92      1.00      0.96        11
           2       1.00      0.83      0.91         6
           3       1.00      1.00      1.00         2

    accuracy                 

C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\


Akurasi SVM One vs All :  0.82

              precision    recall  f1-score   support

           0       0.99      1.00      0.99        75
           1       1.00      0.94      0.97        18
           2       1.00      1.00      1.00         3
           3       1.00      1.00      1.00         4

    accuracy                           0.99       100
   macro avg       1.00      0.99      0.99       100
weighted avg       0.99      0.99      0.99       100

-----------------------------
Banyak Data Latih:  900
Banyak Data Uji:  100

Data Latih: 
 [  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 10

C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\


Hasil Prediksi SVM KERNEL RBF: 
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 1 1 1 0 0 0 0
 1 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0]

Hasil Prediksi SVM One vs All : 
 [0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0]

Confusion Matrix: 
 [[80  1]
 [ 1 18]]

Confusion Matrix: 
 [[78  3]
 [11  8]]

Akurasi SVM RBF:  0.98


Akurasi SVM One vs All :  0.86

              precision    recall  f1-score   support

           0       0.99      0.99      0.99        81
           1       0.95      0.95      0.95        19
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0

   micro avg       0.98      0.98      0.98       100
   macro avg       0.48      0.48      0.48       100
weigh

              precision    recall  f1-score   support

           0       0.93      0.92      0.93        92
           1       0.22      0.25      0.24         8
           2       0.00      0.00      0.00         0
           3       0.00      0.00      0.00         0

   micro avg       0.87      0.87      0.87       100
   macro avg       0.29      0.29      0.29       100
weighted avg       0.88      0.87      0.87       100

Rata-rata akurasi keseluruhan SVM kernel RBF adalah : 0.917


C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\user\AppData\Roaming\Python\Python310\site-packages\sklearn\metrics\_classification.py:1327: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\

IndexError: list index out of range